linters:
  enable-all: true
  exclude-use-default: false
  disable:
    - exhaustivestruct
    - forbidigo
    - golint
    - interfacer
    - maligned
    - scopelint

issues:
  exclude-use-default: false

linters-settings:
  govet:
    check-shadowing: true
  errcheck:
    exclude-functions:
      - (io.Closer).Close
